# Generated by Django 2.2.1 on 2019-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEquipo', models.PositiveSmallIntegerField()),
                ('Nombre', models.CharField(max_length=40)),
                ('Logo', models.CharField(max_length=300)),
                ('Descripcion', models.CharField(max_length=150)),
                ('Patrocinador', models.CharField(max_length=150)),
                ('Dueno', models.CharField(max_length=150)),
                ('Facebook', models.CharField(max_length=300)),
                ('Foto', models.CharField(max_length=300)),
            ],
        ),
    ]
