# Generated by Django 2.2.1 on 2019-05-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEquipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idJugador', models.PositiveSmallIntegerField()),
                ('Nombre', models.CharField(max_length=150)),
                ('Foto', models.CharField(max_length=300)),
                ('Edad', models.PositiveSmallIntegerField()),
                ('Telefono', models.CharField(max_length=10)),
                ('Facebook', models.CharField(max_length=300)),
                ('NumeroJugador', models.PositiveSmallIntegerField()),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEquipos.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEntrenador', models.PositiveSmallIntegerField()),
                ('Nombre', models.CharField(max_length=150)),
                ('Foto', models.CharField(max_length=300)),
                ('Edad', models.PositiveSmallIntegerField()),
                ('Telefono', models.CharField(max_length=10)),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEquipos.Equipo')),
            ],
        ),
    ]
